[build]
  command = "yarn build"
  publish = "out"
[[plugins]]
  package = "@netlify/plugin-nextjs"
[[redirects]]
  from = "/api"
  to = "https://654f4ad5-359f-4f12-b9ee-33099582e6d3-europe-west1.apps.astra.datastax.com/api/graphql/garbage"
  status = 200
