# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  cache-version: v20200524
  YARN_CACHE: 'true'

jobs:
  yarn-install:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - macos-10.15
          - windows-2019
        node-version:
          - 12.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        if: env.YARN_CACHE == 'true'
      - uses: actions/setup-node@v1
        if: env.YARN_CACHE == 'true'
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn offline cache
        uses: actions/cache@v1
        id: yarn-offline-cache
        if: env.YARN_CACHE == 'true'
        with:
          path: ~/yarn-offline-cache
          key: ${{ env.cache-version }}-yarn-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ env.cache-version }}-yarn-${{ matrix.os }}-${{ matrix.node-version }}-
      - name: Install packages
        if: env.YARN_CACHE == 'true'
        run: |
          yarn config set network-timeout 300000
          yarn config set yarn-offline-mirror ./yarn-offline-cache
          yarn config set yarn-offline-mirror-pruning true
          yarn install --frozen-lockfile --prefer-offline

  lint:
    needs: yarn-install
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        node-version:
          - 12.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn offline cache
        uses: actions/cache@v1
        id: yarn-offline-cache
        if: env.YARN_CACHE == 'true'
        with:
          path: ~/yarn-offline-cache
          key: ${{ env.cache-version }}-yarn-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ env.cache-version }}-yarn-${{ matrix.os }}-${{ matrix.node-version }}-
      - name: Install packages
        run: |
          yarn config set network-timeout 300000
          yarn config set yarn-offline-mirror ./yarn-offline-cache
          yarn config set yarn-offline-mirror-pruning true
          yarn install --frozen-lockfile --prefer-offline
      - run: yarn lint
        continue-on-error: true

  unit-test:
    needs: yarn-install
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - macos-10.15
          - windows-2019
        node-version:
          - 12.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn offline cache
        uses: actions/cache@v1
        id: yarn-offline-cache
        if: env.YARN_CACHE == 'true'
        with:
          path: ~/yarn-offline-cache
          key: ${{ env.cache-version }}-yarn-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ env.cache-version }}-yarn-${{ matrix.os }}-${{ matrix.node-version }}-
      - name: Install packages
        run: |
          yarn config set network-timeout 300000
          yarn config set yarn-offline-mirror ./yarn-offline-cache
          yarn config set yarn-offline-mirror-pruning true
          yarn install --frozen-lockfile --prefer-offline
      - run: yarn test:unit

  e2e-test:
    needs: yarn-install
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - macos-10.15
          - windows-2019
        node-version:
          - 12.x
        browser:
          - chrome
          - edge
        exclude:
          - os: ubuntu-18.04
            browser: edge
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn offline cache
        uses: actions/cache@v1
        id: yarn-offline-cache
        if: env.YARN_CACHE == 'true'
        with:
          path: ~/yarn-offline-cache
          key: ${{ env.cache-version }}-yarn-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ env.cache-version }}-yarn-${{ matrix.os }}-${{ matrix.node-version }}-
      - name: Install packages
        run: |
          yarn config set network-timeout 300000
          yarn config set yarn-offline-mirror ./yarn-offline-cache
          yarn config set yarn-offline-mirror-pruning true
          yarn install --frozen-lockfile --prefer-offline
      - run: yarn build
      - run: yarn export
      - run: yarn cypress info
      - run: yarn start-test start 3001 "cypress run --browser ${{ matrix.browser }}"
      - name: Upload snapshots
        uses: actions/upload-artifact@v1
        with:
          name: snapshots-${{ matrix.os }}-${{ matrix.browser }}
          path: tests/e2e/snapshots

  lighthouse-test:
    needs: yarn-install
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        node-version:
          - 12.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn offline cache
        uses: actions/cache@v1
        id: yarn-offline-cache
        if: env.YARN_CACHE == 'true'
        with:
          path: ~/yarn-offline-cache
          key: ${{ env.cache-version }}-yarn-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ env.cache-version }}-yarn-${{ matrix.os }}-${{ matrix.node-version }}-
      - name: Install packages
        run: |
          yarn config set network-timeout 300000
          yarn config set yarn-offline-mirror ./yarn-offline-cache
          yarn config set yarn-offline-mirror-pruning true
          yarn install --frozen-lockfile --prefer-offline
      - run: yarn build
      - run: yarn export
      - uses: treosh/lighthouse-ci-action@v2
        with:
          uploadArtifacts: true
          temporaryPublicStorage: false
          configPath: './lighthouserc.json'
